---
all:
  hosts:
    R1:
      ansible_host: 192.168.122.2
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.ios.ios
      ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
      ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
      ansible_become: yes
      ansible_become_method: enable
      ansible_ssh_transport: paramiko
      ansible_ssh_common_args: >
        -oKexAlgorithms=diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
        -oCiphers=aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc
        -oHostKeyAlgorithms=ssh-rsa
        -oPubkeyAcceptedAlgorithms=+ssh-rsa
      ansible_command_timeout: 60
      ansible_persistent_connect_timeout: 60
      ansible_persistent_command_timeout: 60
