all:
  hosts:
    R1:
      ansible_host: 192.168.122.2
      ansible_connection: network_cli
      ansible_network_os: ios
      ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
      ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
      ansible_ssh_common_args: "-oKexAlgorithms=diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1"
      ansible_become: yes
      ansible_become_method: enable

