---
- name: Configure and backup router
  hosts: all
  gather_facts: no
  vars_files:
    - ../group_vars/all.yml
  
  tasks:
    - name: Create backups directory
      ansible.builtin.file:
        path: "backups/"
        state: directory
      delegate_to: localhost
      run_once: true
      
    - name: Backup config
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: config_output
      tags: backup
      
    - name: Verify config was captured
      assert:
        that:
          - config_output.stdout[0] | length > 1000
        fail_msg: "Config backup appears incomplete"
      
    - name: Save config File
      ansible.builtin.copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "backups/{{ inventory_hostname }}_backup-{{ ansible_date_time.date }}.txt"
      delegate_to: localhost
      tags: backup
      
    - name: Ping test server
      cisco.ios.ios_command:
        commands:
          - ping {{ test_ping }} repeat 4
      register: ping_test
      failed_when: "'!!' not in ping_test.stdout[0]"
      
    - name: Show Ping results
      debug:
        var: ping_test.stdout_lines
