---
- name: Configure and backup router
  hosts: all
  gather_facts: no
  tasks:
    - name:
      ansible.builtin.file:
        path: "backups/"
        state: directory
      delegate_to: localhost
      run_once: true
      
    - name: Backup config
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: config_output
      
    - name: Save config File
      ansible.builtin.copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "backups/{{ inventory_hostname }}_backup-{{ ansible_date_time.date }}.txt"
      delegate_to: localhost
      
    - name: Ping 8.8.8.8
      ios_command:
        commands:
          - ping 8.8.8.8 repeat 4
      register: ping_test
      failed_when: "'!!' not in ping_test.stdout[0]"
      
    - name: Show Ping
      debug:
        var: ping_test.stdout_lines
