name: Network Automation

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * 1"  # Weekly at 3 AM Monday

jobs:
  configure-network:
    runs-on: [self-hosted, network-lab-runner]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Clean Python environment
        run: |
          pip uninstall -y ansible ansible-core ansible-pylibssh paramiko cryptography six || true
          rm -rf ~/.ansible
          rm -rf ~/.cache/pip
          pip cache purge

      - name: Install Ansible 2.9 with dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "ansible==2.9.27" "paramiko==2.7.1" "cryptography==3.3.2" "six==1.16.0"
          
          # Create complete six module structure
          SIX_PATH=$(python -c "import ansible.module_utils; print(ansible.module_utils.__path__[0])")
          mkdir -p "$SIX_PATH/six/moves"
          cat > "$SIX_PATH/six/__init__.py" <<EOF
          from __future__ import absolute_import
          from six import *
          EOF
          touch "$SIX_PATH/six/moves/__init__.py"
          
          # Verify installation
          python -c "from ansible.module_utils.six.moves import urllib; print('Six.moves import successful')"

      - name: Install Cisco IOS collection
        run: |
          mkdir -p ~/.ansible/collections
          ansible-galaxy collection install cisco.ios -p ~/.ansible/collections

      - name: Install SSH dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Verify environment
        run: |
          python -c "from ansible.module_utils.six.moves import urllib; print('Six.moves verification successful')"
          ansible --version
          ansible-galaxy collection list
          ls -la ~/.ansible/collections/ansible_collections/cisco/ios

      - name: Run Ansible Playbook
        env:
          ANSIBLE_CONFIG: "$GITHUB_WORKSPACE/ansible.cfg"
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3"
          ANSIBLE_LIBRARY: "/home/runner/.ansible/collections/ansible_collections/cisco/ios/plugins/modules"
        run: |
          ansible-playbook -i inventory/production.yml playbooks/configure_devices.yml -vvv

      - name: Commit and Push Backups
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "coopercopper@gmail.com"
          git add backups/
          git diff-index --quiet HEAD || git commit -m "Automated backup: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
