on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * 1" 

jobs:
  configure-network:
    runs-on: [self-hosted, network-lab-runner] 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Ansible
        run: pip install ansible

      - name: Install Ansible with dependencies
        run: |
          pip install ansible ansible-pylibssh
          ansible-galaxy collection install cisco.ios

      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i inventory/production.yml playbooks/configure_devices.yml

      - name: Commit and Push Backups
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "coopercopper@gmail.com"
          git add backups/
          git diff-index --quiet HEAD || git commit -m "Automated backup: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
