name: Network Automation

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * 1"  # Weekly at 3 AM Monday

jobs:
  configure-network:
    runs-on: [self-hosted, network-lab-runner]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Clean Python environment
        run: |
          pip uninstall -y ansible ansible-core ansible-pylibssh paramiko cryptography six || true
          pip cache purge

      - name: Install stable Ansible stack
        run: |
          python -m pip install --upgrade pip
          pip install "ansible==2.9.27" "paramiko==2.7.1" "cryptography==3.3.2" "six==1.16.0"
          ansible-galaxy collection install cisco.ios
          
          # Force install six in ansible's module_utils
          SIX_PATH=$(python -c "import ansible.module_utils; print(ansible.module_utils.__path__[0])")
          pip install --target="$SIX_PATH" "six==1.16.0"

      - name: Verify six installation
        run: |
          python -c "from ansible.module_utils import six; print('six module found at:', six.__file__)"
          ansible --version
          ansible-galaxy collection list

      - name: Install SSH dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Run Ansible Playbook
        env:
          ANSIBLE_CONFIG: "$GITHUB_WORKSPACE/ansible.cfg"
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i inventory/production.yml playbooks/configure_devices.yml -vvv

      - name: Commit and Push Backups
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "coopercopper@gmail.com"
          git add backups/
          git diff-index --quiet HEAD || git commit -m "Automated backup: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
