name: Network Automation

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * 1"  # Weekly at 3 AM Monday

jobs:
  configure-network:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python & Ansible
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
        run: |
          pip install ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
        run: |
          ansible-playbook -i inventory/production.ini playbooks/configure_devices.yml

      - name: Commit Backups
        run: |
          git config --global user.name "gitkhanab"
          git config --global user.email "coopercopper@gmail.com"
          git add backups/
          git commit -m "Automated backup: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
