name: Network Automation

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 3 * * 1"  # Weekly at 3 AM Monday

jobs:
  configure-network:
    runs-on: [self-hosted, network-lab-runner]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Legacy-Compatible Packages
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y ansible ansible-core
          pip install ansible-core==2.12.10 paramiko==2.7.1
          ansible-galaxy collection install cisco.ios:==4.5.0
          pip install sshpass

      - name: Install SSH dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Run Ansible Playbook
        env:
          ANSIBLE_CONFIG: "$GITHUB_WORKSPACE/ansible.cfg"
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          ANSIBLE_TRANSPORT: paramiko
          ANSIBLE_NETWORK_CLI_SSH_TYPE: paramiko
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_PARAMIKO_LOOK_FOR_KEYS: "False"
          ANSIBLE_SSH_ARGS: "-oKexAlgorithms=diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1 -oCiphers=aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc -oHostKeyAlgorithms=ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa"
        run: |
          ansible-playbook -vvvv \
            -e "ansible_connection=ansible.netcommon.network_cli" \
            -e "ansible_network_os=cisco.ios.ios" \
            -e "ansible_ssh_transport=paramiko" \
            -i inventory/production.yml \
            playbooks/configure_devices.yml

      - name: Commit and Push Backups
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add backups/
          git diff-index --quiet HEAD || git commit -m "Automated backup: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
