name: Network Automation

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * 1"  # Weekly at 3 AM Monday

jobs:
  configure-network:
    runs-on: [self-hosted, network-lab-runner]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Clean Python environment
        run: |
          pip uninstall -y ansible ansible-core || true
          rm -rf ~/.ansible
          rm -rf ~/.cache/pip
          pip cache purge

      - name: Install Modern Ansible Stack
        run: |
          python -m pip install --upgrade pip
          pip install "ansible-core==2.14.10" "ansible==8.6.0"
          pip install paramiko
          
          # Install Cisco IOS collection directly (bypass ansible-galaxy if needed)
          mkdir -p ~/.ansible/collections/ansible_collections/cisco/ios
          git clone https://github.com/ansible-collections/cisco.ios.git ~/.ansible/collections/ansible_collections/cisco/ios

      - name: Install SSH dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Verify environment
        run: |
          ansible --version
          python -c "from ansible.utils.collection_loader import AnsibleCollectionLoader; print('Collections loader working')"
          ls -la ~/.ansible/collections/ansible_collections/cisco/ios

      - name: Run Ansible Playbook
        env:
          ANSIBLE_CONFIG: "$GITHUB_WORKSPACE/ansible.cfg"
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_PASSWORD: ${{ secrets.ANSIBLE_PASSWORD }}
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i inventory/production.yml playbooks/configure_devices.yml -vvv

      - name: Commit and Push Backups
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "coopercopper@gmail.com"
          git add backups/
          git diff-index --quiet HEAD || git commit -m "Automated backup: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
